name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          build-number: ${{ github.run_number }}

      - name: Prepare APK Release
        id: find_apk
        run: |
          APK_PATH=$(find ${{ steps.build.outputs.output-path }} -name "*.apk" | head -n 1)
          CLEAN_NAME="HandOver-v1.0.${{ github.run_number }}.apk"
          cp "$APK_PATH" "$CLEAN_NAME"
          echo "apk_path=$CLEAN_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Hand Over Pertamina v1.0.${{ github.run_number }}"
          body: |
            ### ?? Rilis Aplikasi Android (.apk)
            Silakan unduh file APK di bawah ini dan langsung pasang (install) di perangkat Android Anda.
          files: ${{ steps.find_apk.outputs.apk_path }}
          draft: false
          prerelease: false

